on:
  push:
    tags:
      - "v*"

name: Build and push release image to github container registry

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build \
            --compress \
            --tag ghcr.io/musicmash/web-ui:${GITHUB_REF##*/} \
            .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MUSICMASH_CONTAINER_REGISTRY_PAT }}

      - name: Push image to GitHub Container Registry
        run: |
          docker push ghcr.io/musicmash/web-ui:${GITHUB_REF##*/}

