on: [push]
on:
  push:
    branches:
      - master

name: Build and push fe image

jobs:
  build:
    name: Build and push fe image to github packages and docker hub
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pull latest images
        run: |
          docker pull $IMAGE_NAME:latest || true
          docker pull $IMAGE_NAME-builder-stage:latest || true

      - name: Build the Docker image
        run: |
          docker build \
            --target builder \
            --cache-from $IMAGE_NAME-builder-stage:latest \
            -t $IMAGE_NAME-builder-stage \
            .
          docker build \
            --cache-from $IMAGE_NAME-builder-stage:latest \
            --cache-from $IMAGE_NAME:latest \
            --tag $IMAGE_NAME:latest \
            --tag docker.pkg.github.com/$IMAGE_NAME/web-ui:latest \
            .

      - name: Login to hubs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKERHUB_ACTOR: ${{ secrets.DOCKERHUB_ACTOR }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker login docker.pkg.github.com -u $GITHUB_ACTOR    -p $GITHUB_TOKEN
          docker login                       -u $DOCKERHUB_ACTOR -p $DOCKERHUB_TOKEN

      - name: Push image to hubs
        run: |
          docker push $IMAGE_NAME-builder-stage:latest
          docker push $IMAGE_NAME:latest
          docker push docker.pkg.github.com/$IMAGE_NAME/web-ui:latest

      - name: Tag image with git tag if exists
        if: github.event_name == 'push' && github.event.ref_type == 'tag'
        run: |
          GIT_TAG="${GITHUB_REF#refs/tags/}"

          docker tag $IMAGE_NAME:latest $IMAGE_NAME:$GIT_TAG
          docker tag $IMAGE_NAME:latest docker.pkg.github.com/$IMAGE_NAME/web-ui:$GIT_TAG

          docker push $IMAGE_NAME:$GIT_TAG
          docker push docker.pkg.github.com/$IMAGE_NAME/web-ui:$GIT_TAG

      - name: Logout
        run: |
          docker logout docker.pkg.github.com
          docker logout
